CONFIG_ZMK_POINTING=y
CONFIG_BB_TRACKBALL=y

# USB serial logging - read with: screen /dev/ttyACM0 115200
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_INPUT_LOG_LEVEL_DBG=y
